# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.f_psi_arma <- function(x, data, psi) {
    .Call(`_rankCluster_f_psi_cpp`, x, data, psi)
}

.f_theta_arma <- function(x, data, theta, psi) {
    .Call(`_rankCluster_f_theta_cpp`, x, data, theta, psi)
}

.rel_eff_arma <- function(data, theta, psi) {
    .Call(`_rankCluster_rel_eff_cpp`, data, theta, psi)
}

.sigma_est_arma <- function(n, data, theta, psi) {
    .Call(`_rankCluster_sigma_est_cpp`, n, data, theta, psi)
}

.q_wald_arma <- function(n, data, theta, psi, cmat) {
    .Call(`_rankCluster_q_wald_arma`, n, data, theta, psi, cmat)
}

.q_anova_arma <- function(n, data, theta, psi, cmat) {
    .Call(`_rankCluster_q_anova_arma`, n, data, theta, psi, cmat)
}

